name: Publish ARM64 Image

on:
  # Run the workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      image_name:
        description: 'Enter the name of the image to build:'
        type: string
        required: true
        default: ''

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

run-name:  'Publish Image: ${{ inputs.image_name }}'

jobs:
  build:

    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: |
          git checkout -b ${{ inputs.image_name }}

      - run: |
          security -v unlock-keychain ~/Library/Keychains/login.keychain-db

      - run: |
          brew install docker docker-machine
          brew cask install virtualbox
          docker-machine create --driver virtualbox default
          docker-machine env default

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.image_name }}

      # Build and push Docker image with Buildx
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ inputs.image_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
